### ISSUE TITLE
Can't find cut-corpus python file in make-data.sh

### ISSUE THREAD

**Issue by ruanqin0706** [cindyxinyiwang/SDE#2]
https://github.com/cindyxinyiwang/SDE/blob/33834123eb130730791a6b786d34bcd669d9eb5e/make-data.sh#L45-L46

I just can't find cut-corpus.py under SDE project, could you check and let me know where is it? 

Thanks in advanced!

**Comment by cindyxinyiwang** [comment]
Sorry for the late reply! For some reason I didn't get notification for the issues. I just pushed the python file.
